### ISSUE TITLE
Max upload file size is constrained to 1Mb by spring boot

### ISSUE THREAD

**Issue by yannou38** [jveverka/file-server#7]
The max upload file size is constrained by spring boot to 1Mb. Could you add a setting that would be applied to spring boot so this limit can be raised ?

**Comment by yannou38** [comment]
Update:

adding the following in the application.yml solve the problem. I'm not knowledgeable about spring boot and didn't realize it would be this easy

```
spring:
  servlet:
    multipart:
      # max single file size
      max-file-size: 100MB
      # max request size
      max-request-size: 200MB

```
